service: noteme

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  deploymentMethod: direct
  stage: production
  runtime: nodejs18.x
  region: sa-east-1

package:
  excludeDevDependencies: true

functions:
  graphql:
    handler: src/serverless.handler
    events:
      - http:
          path: /graphql
          method: any
          cors: true
