service: noteme-api

useDotenv: true

plugins:
  - serverless-offline
  - serverless-bundle

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x
  region: sa-east-1
  deploymentBucket:
    name: noteme
  environment:
    NODE_ENV: ${env:NODE_ENV}
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

package:
  excludeDevDependencies: true

custom:
  bundle:
    linting: false
    excludeFiles: '**/*.spec.ts'
    externals: all
    copyFiles:
      - from: 'prisma/schema.prisma'
        to: './src'
    packagerOptions:
      scripts:
        - prisma generate && rimraf node_modules/@prisma/engines/** && rimraf node_modules/prisma/libquery_engine-[^rhel]* && prisma db push

functions:
  graphql:
    handler: src/serverless.handler
    events:
      - http:
          path: /graphql
          method: any
