service: noteme
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-monorepo

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

package:
  individually: true

functions:
  graphql:
    handler: src/main.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
